services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: n8n-shankar.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-shankar.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
